""
"" Janus setup
""

" Define paths
let g:janus_path = escape(fnamemodify(resolve(expand("<sfile>:p")), ":h"), ' ')
let g:janus_vim_path = escape(fnamemodify(resolve(expand("<sfile>:p" . "vim")), ":h"), ' ')
let g:janus_custom_path = expand("~/.janus")

" Source janus's core
exe 'source ' . g:janus_vim_path . '/core/before/plugin/janus.vim'

" You should note that groups will be processed by Pathogen in reverse
" order they were added.
call janus#add_group("tools")
call janus#add_group("langs")
call janus#add_group("colors")

""
"" Customisations
""

if filereadable(expand("~/.vimrc.before"))
  source ~/.vimrc.before
endif


" Disable plugins prior to loading pathogen
exe 'source ' . g:janus_vim_path . '/core/plugins.vim'

""
"" Pathogen setup
""

" Load all groups, custom dir, and janus core
call janus#load_pathogen()

" .vimrc.after is loaded after the plugins have loaded
syntax on
set number 

syntax enable
set showcmd
set shiftwidth=2
set tabstop=2
set expandtab
set autoindent

colorscheme molokai
set background=dark
set nowrap
set iskeyword+=-

inoremap <Nul> <C-n>
:map <F2> :set autoindent! <CR>
:map <F3> :set number! <CR>
:map <F4> :NERDTree <CR>
:map <F5> :set noexpandtab<CR>
:map <tab> <C-W>w
:map <S-tab> <C-W>h
autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p

